### ISSUE TITLE
Fix coveralls CI integration

### ISSUE THREAD

**Issue by crowesn** [uclibs/treatment_database#324]
Coveralls coverage reports fail to upload 
```bash
#!/bin/bash -eo pipefail curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$CIRCLE_BUILD_NUM&payload[status]=done"  
{"error":"No build matching CI build number 1012 found"}
CircleCI received exit code 0
```

**Comment by hortongn** [comment]
Not sure if this is related to the CI problem, but I see this Coveralls/simplecov error when the specs finish running on my local machine:

```
Coverage report generated for RSpec to /Users/hortongn/Development/uclibs/treatment_database/coverage. 449 / 468 LOC (95.94%) covered.
[Coveralls] Outside the CI environment, not sending data.
Traceback (most recent call last):
        3: from /Users/hortongn/.rvm/gems/ruby-2.7.6@treatment/gems/simplecov-0.16.1/lib/simplecov/defaults.rb:27:in `block in <top (required)>'
        2: from /Users/hortongn/.rvm/gems/ruby-2.7.6@treatment/gems/simplecov-0.16.1/lib/simplecov.rb:202:in `run_exit_tasks!'
        1: from /Users/hortongn/.rvm/gems/ruby-2.7.6@treatment/gems/simplecov-0.16.1/lib/simplecov.rb:219:in `process_result'
/Users/hortongn/.rvm/gems/ruby-2.7.6@treatment/gems/simplecov-0.16.1/lib/simplecov.rb:238:in `result_exit_status': undefined method `-' for nil:NilClass (NoMethodError)
```

**Comment by crowesn** [comment]
https://docs.coveralls.io/parallel-build-webhook#circleci-setup
